[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["dotnet restore Mjolksyra.Api/Mjolksyra.Api.csproj"]

[phases.build]
cmds = ["dotnet publish Mjolksyra.Api/Mjolksyra.Api.csproj -c Release -o out"]

[start]
cmd = "dotnet out/Mjolksyra.Api.dll --urls http://0.0.0.0:$PORT"
