[build]
builder = "DOCKERFILE"
dockerfilePath = "Mjolksyra.Api/Dockerfile"

[deploy]
startCommand = "dotnet Mjolksyra.Api.dll"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
